export const cityDistricts = [
  {
    city: "Adana",
    districts: [
      "Seyhan",
      "Yüreğir",
      "Çukurova",
      "Kozan",
      "Ceyhan",
      "Feke",
      "Karaisalı",
      "Aladağ",
      "Pozantı",
      "Sarıçam",
      "Tufanbeyli",
    ],
  },
  {
    city: "Adıyaman",
    districts: [
      "Merkez",
      "Kahta",
      "Besni",
      "Gerger",
      "Gölbaşı",
      "Çelikhan",
      "Samsat",
      "Tut",
    ],
  },
  {
    city: "Afyonkarahisar",
    districts: [
      "Merkez",
      "Sandıklı",
      "Dinar",
      "Emirdağ",
      "İhsaniye",
      "Bayat",
      "Bolvadin",
      "Çay",
      "Hocalar",
      "Kızılören",
      "Şuhut",
    ],
  },
  {
    city: "Ağrı",
    districts: [
      "Merkez",
      "Doğubayazıt",
      "Patnos",
      "Taşlıçay",
      "Diyadin",
      "Eleşkirt",
      "Hamur",
      "Tutak",
    ],
  },
  {
    city: "Amasya",
    districts: [
      "Merkez",
      "Suluova",
      "Gümüşhacıköy",
      "Merzifon",
      "Hamamözü",
      "Taşova",
      "Göynücek",
    ],
  },
  {
    city: "Ankara",
    districts: [
      "Çankaya",
      "Keçiören",
      "Yenimahalle",
      "Mamak",
      "Sincan",
      "Altındağ",
      "Etimesgut",
      "Pursaklar",
      "Gölbaşı",
      "Polatlı",
      "Çubuk",
      "Beypazarı",
      "Elmadağ",
      "Kızılcahamam",
      "Akyurt",
      "Haymana",
      "Nallıhan",
      "Şereflikoçhisar",
      "Kalecik",
      "Ayaş",
      "Bala",
      "Güdül",
      "Kahramankazan",
      "Evren",
    ],
  },
  {
    city: "Antalya",
    districts: [
      "Muratpaşa",
      "Kepez",
      "Konyaaltı",
      "Aksu",
      "Alanya",
      "Kemer",
      "Serik",
      "Manavgat",
      "Kumluca",
      "Finike",
      "Demre",
      "Kaş",
      "Döşemealtı",
    ],
  },
  {
    city: "Artvin",
    districts: [
      "Merkez",
      "Hopa",
      "Borçka",
      "Ardanuç",
      "Murgul",
      "Şavşat",
      "Yusufeli",
    ],
  },
  {
    city: "Aydın",
    districts: [
      "Efeler",
      "Nazilli",
      "Söke",
      "Kuşadası",
      "Didim",
      "İncirliova",
      "Çine",
      "Germencik",
      "Bozdoğan",
      "Karpuzlu",
      "Koçarlı",
      "Kuyucak",
      "Sultanhisar",
      "Yenipazar",
    ],
  },
  {
    city: "Balıkesir",
    districts: [
      "Altıeylül",
      "Karesi",
      "Edremit",
      "Bandırma",
      "Gönen",
      "Ayvalık",
      "Burhaniye",
      "Bigadiç",
      "Susurluk",
      "Dursunbey",
      "Sındırgı",
      "Erdek",
      "Havran",
      "İvrindi",
      "Manyas",
      "Balya",
      "Gömeç",
      "Marmara",
      "Savaştepe",
    ],
  },
  {
    city: "Bilecik",
    districts: [
      "Merkez",
      "Bozüyük",
      "Osmaneli",
      "Söğüt",
      "Gölpazarı",
      "Pazaryeri",
      "İnhisar",
      "Yenipazar",
    ],
  },
  {
    city: "Bingöl",
    districts: [
      "Merkez",
      "Genç",
      "Solhan",
      "Karlıova",
      "Adaklı",
      "Kiğı",
      "Yayladere",
      "Yedisu",
    ],
  },
  {
    city: "Bitlis",
    districts: [
      "Merkez",
      "Tatvan",
      "Ahlat",
      "Hizan",
      "Güroymak",
      "Mutki",
      "Adilcevaz",
    ],
  },
  {
    city: "Bolu",
    districts: [
      "Merkez",
      "Gerede",
      "Mengen",
      "Göynük",
      "Dörtdivan",
      "Yeniçağa",
      "Mudurnu",
      "Seben",
    ],
  },
  {
    city: "Burdur",
    districts: [
      "Merkez",
      "Bucak",
      "Gölhisar",
      "Yeşilova",
      "Çavdır",
      "Tefenni",
      "Ağlasun",
      "Karamanlı",
      "Altınyayla",
    ],
  },
  {
    city: "Bursa",
    districts: [
      "Osmangazi",
      "Yıldırım",
      "Nilüfer",
      "İnegöl",
      "Gemlik",
      "Mustafakemalpaşa",
      "Mudanya",
      "Gürsu",
      "Kestel",
      "Orhangazi",
      "Karacabey",
      "Yenişehir",
      "İznik",
      "Orhaneli",
      "Büyükorhan",
      "Harmancık",
      "Keles",
    ],
  },
  {
    city: "Çanakkale",
    districts: [
      "Merkez",
      "Biga",
      "Çan",
      "Gelibolu",
      "Ezine",
      "Yenice",
      "Bayramiç",
      "Ayvacık",
      "Lapseki",
      "Eceabat",
      "Gökçeada",
      "Bozcaada",
    ],
  },
  {
    city: "Çankırı",
    districts: [
      "Merkez",
      "Çerkeş",
      "Ilgaz",
      "Kurşunlu",
      "Orta",
      "Şabanözü",
      "Yapraklı",
      "Atkaracalar",
      "Eldivan",
      "Kızılırmak",
      "Bayramören",
    ],
  },
  {
    city: "Çorum",
    districts: [
      "Merkez",
      "Alaca",
      "Bayat",
      "İskilip",
      "Kargı",
      "Mecitözü",
      "Ortaköy",
      "Osmancık",
      "Sungurlu",
      "Boğazkale",
      "Uğurludağ",
      "Dodurga",
      "Laçin",
      "Oğuzlar",
    ],
  },
  {
    city: "Denizli",
    districts: [
      "Merkez",
      "Pamukkale",
      "Çivril",
      "Acıpayam",
      "Tavas",
      "Buldan",
      "Çal",
      "Sarayköy",
      "Honaz",
      "Serinhisar",
      "Bozkurt",
      "Güney",
      "Bekilli",
      "Çardak",
      "Çameli",
      "Babadağ",
      "Baklan",
      "Beyağaç",
      "Kale",
    ],
  },
  {
    city: "Diyarbakır",
    districts: [
      "Bağlar",
      "Bismil",
      "Çermik",
      "Çınar",
      "Çüngüş",
      "Dicle",
      "Eğil",
      "Ergani",
      "Hani",
      "Hazro",
      "Kayapınar",
      "Kocaköy",
      "Kulp",
      "Lice",
      "Silvan",
      "Sur",
      "Yenişehir",
    ],
  },
  {
    city: "Edirne",
    districts: [
      "Merkez",
      "Keşan",
      "Uzunköprü",
      "Havsa",
      "İpsala",
      "Enez",
      "Süloğlu",
      "Lalapaşa",
      "Meriç",
    ],
  },
  {
    city: "Elazığ",
    districts: [
      "Merkez",
      "Kovancılar",
      "Karakoçan",
      "Maden",
      "Palu",
      "Arıcak",
      "Baskil",
      "Sivrice",
      "Alacakaya",
      "Keban",
      "Ağın",
    ],
  },
  {
    city: "Erzincan",
    districts: [
      "Merkez",
      "Tercan",
      "Üzümlü",
      "Çayırlı",
      "İliç",
      "Kemah",
      "Kemaliye",
      "Refahiye",
      "Otlukbeli",
    ],
  },
  {
    city: "Erzurum",
    districts: [
      "Yakutiye",
      "Palandöken",
      "Aziziye",
      "Horasan",
      "Oltu",
      "Pasinler",
      "Karayazı",
      "Hınıs",
      "Tekman",
      "Karaçoban",
      "Aşkale",
      "Şenkaya",
      "Çat",
      "Olur",
      "İspir",
      "Narman",
      "Tortum",
      "Uzundere",
      "Pazaryolu",
      "Köprüköy",
    ],
  },
  {
    city: "Eskişehir",
    districts: [
      "Odunpazarı",
      "Tepebaşı",
      "Seyitgazi",
      "Çifteler",
      "Mahmudiye",
      "Mihalıççık",
      "Alpu",
      "Beylikova",
      "İnönü",
      "Günyüzü",
      "Han",
      "Mihalgazi",
      "Sarıcakaya",
    ],
  },
  {
    city: "Gaziantep",
    districts: [
      "Şahinbey",
      "Şehitkamil",
      "Nizip",
      "İslahiye",
      "Nurdağı",
      "Araban",
      "Oğuzeli",
      "Yavuzeli",
      "Karkamış",
    ],
  },
  {
    city: "Giresun",
    districts: [
      "Merkez",
      "Bulancak",
      "Espiye",
      "Görele",
      "Tirebolu",
      "Dereli",
      "Şebinkarahisar",
      "Yağlıdere",
      "Piraziz",
      "Eynesil",
      "Keşap",
      "Çanakçı",
      "Doğankent",
      "Güce",
      "Alucra",
      "Çamoluk",
    ],
  },
  {
    city: "Gümüşhane",
    districts: ["Merkez", "Kelkit", "Şiran", "Köse", "Kürtün", "Torul"],
  },
  {
    city: "Hakkari",
    districts: ["Merkez", "Yüksekova", "Çukurca", "Şemdinli"],
  },
  {
    city: "Hatay",
    districts: [
      "Antakya",
      "İskenderun",
      "Defne",
      "Dörtyol",
      "Reyhanlı",
      "Samandağ",
      "Kırıkhan",
      "Altınözü",
      "Hassa",
      "Payas",
      "Erzin",
      "Belen",
      "Kumlu",
      "Yayladağı",
    ],
  },
  {
    city: "Iğdır",
    districts: ["Merkez", "Aralık", "Tuzluca", "Karakoyunlu"],
  },
  {
    city: "Isparta",
    districts: [
      "Merkez",
      "Yalvaç",
      "Eğirdir",
      "Şarkikaraağaç",
      "Gelendost",
      "Keçiborlu",
      "Senirkent",
      "Sütçüler",
      "Gönen",
      "Uluborlu",
      "Atabey",
      "Aksu",
      "Yenişarbademli",
    ],
  },
  {
    city: "İstanbul",
    districts: [
      "Adalar",
      "Arnavutköy",
      "Ataşehir",
      "Avcılar",
      "Bağcılar",
      "Bahçelievler",
      "Bakırköy",
      "Başakşehir",
      "Bayrampaşa",
      "Beşiktaş",
      "Beykoz",
      "Beylikdüzü",
      "Beyoğlu",
      "Büyükçekmece",
      "Çatalca",
      "Çekmeköy",
      "Esenler",
      "Esenyurt",
      "Eyüpsultan",
      "Fatih",
      "Gaziosmanpaşa",
      "Güngören",
      "Kadıköy",
      "Kağıthane",
      "Kartal",
      "Küçükçekmece",
      "Maltepe",
      "Pendik",
      "Sancaktepe",
      "Sarıyer",
      "Silivri",
      "Sultanbeyli",
      "Sultangazi",
      "Şile",
      "Şişli",
      "Tuzla",
      "Ümraniye",
      "Üsküdar",
      "Zeytinburnu",
    ],
  },
  {
    city: "İzmir",
    districts: [
      "Aliağa",
      "Balçova",
      "Bayındır",
      "Bayraklı",
      "Bergama",
      "Beydağ",
      "Bornova",
      "Buca",
      "Çeşme",
      "Çiğli",
      "Dikili",
      "Foça",
      "Gaziemir",
      "Güzelbahçe",
      "Karabağlar",
      "Karaburun",
      "Karşıyaka",
      "Kemalpaşa",
      "Kınık",
      "Kiraz",
      "Konak",
      "Menderes",
      "Menemen",
      "Narlıdere",
      "Ödemiş",
      "Seferihisar",
      "Selçuk",
      "Tire",
      "Torbalı",
      "Urla",
    ],
  },
  {
    city: "Kahramanmaraş",
    districts: [
      "Onikişubat",
      "Dulkadiroğlu",
      "Elbistan",
      "Afşin",
      "Andırın",
      "Pazarcık",
      "Türkoğlu",
      "Çağlayancerit",
      "Göksun",
      "Nurhak",
      "Ekinözü",
    ],
  },
  {
    city: "Karabük",
    districts: [
      "Merkez",
      "Safranbolu",
      "Yenice",
      "Eflani",
      "Eskipazar",
      "Ovacık",
    ],
  },
  {
    city: "Karaman",
    districts: [
      "Merkez",
      "Ermenek",
      "Ayrancı",
      "Başyayla",
      "Sarıveliler",
      "Kazımkarabekir",
    ],
  },
  {
    city: "Kars",
    districts: [
      "Merkez",
      "Kağızman",
      "Sarıkamış",
      "Akyaka",
      "Digor",
      "Arpaçay",
      "Selim",
      "Susuz",
    ],
  },
  {
    city: "Kastamonu",
    districts: [
      "Merkez",
      "Tosya",
      "Taşköprü",
      "Cide",
      "İnebolu",
      "Araç",
      "Devrekani",
      "Bozkurt",
      "Doğanyurt",
      "Azdavay",
      "Çatalzeytin",
      "Daday",
      "Küre",
      "Şenpazar",
      "Abana",
      "Ağlı",
      "Hanönü",
      "Pınarbaşı",
      "Seydiler",
    ],
  },
  {
    city: "Kayseri",
    districts: [
      "Melikgazi",
      "Kocasinan",
      "Talas",
      "Develi",
      "Yahyalı",
      "Bünyan",
      "İncesu",
      "Pınarbaşı",
      "Tomarza",
      "Yeşilhisar",
      "Sarıoğlan",
      "Hacılar",
      "Sarız",
      "Akkışla",
      "Felahiye",
      "Özvatan",
    ],
  },
  {
    city: "Kırıkkale",
    districts: [
      "Merkez",
      "Delice",
      "Keskin",
      "Sulakyurt",
      "Bahşili",
      "Balışeyh",
      "Çelebi",
      "Karakeçili",
      "Yahşihan",
    ],
  },
  {
    city: "Kırklareli",
    districts: [
      "Merkez",
      "Babaeski",
      "Demirköy",
      "Kofçaz",
      "Lüleburgaz",
      "Pehlivanköy",
      "Pınarhisar",
      "Vize",
    ],
  },
  {
    city: "Kırşehir",
    districts: [
      "Merkez",
      "Çiçekdağı",
      "Kaman",
      "Mucur",
      "Akpınar",
      "Boztepe",
      "Akçakent",
    ],
  },
  {
    city: "Kocaeli",
    districts: [
      "İzmit",
      "Gebze",
      "Darıca",
      "Körfez",
      "Gölcük",
      "Karamürsel",
      "Kandıra",
      "Başiskele",
      "Çayırova",
      "Derince",
      "Dilovası",
    ],
  },
  {
    city: "Konya",
    districts: [
      "Selçuklu",
      "Meram",
      "Karatay",
      "Ereğli",
      "Akşehir",
      "Beyşehir",
      "Çumra",
      "Seydişehir",
      "Ilgın",
      "Cihanbeyli",
      "Kulu",
      "Karapınar",
      "Sarayönü",
      "Yunak",
      "Emirgazi",
      "Hüyük",
      "Doğanhisar",
      "Altınekin",
      "Hadim",
      "Çeltik",
      "Tuzlukçu",
      "Derebucak",
      "Taşkent",
      "Ahırlı",
      "Güneysınır",
      "Yalıhüyük",
      "Halkapınar",
    ],
  },
  {
    city: "Kütahya",
    districts: [
      "Merkez",
      "Simav",
      "Tavşanlı",
      "Emet",
      "Gediz",
      "Altıntaş",
      "Domaniç",
      "Hisarcık",
      "Aslanapa",
      "Çavdarhisar",
      "Pazarlar",
      "Şaphane",
      "Dumlupınar",
    ],
  },
  {
    city: "Malatya",
    districts: [
      "Kale",
      "Battalgazi",
      "Yeşilyurt",
      "Darende",
      "Akçadağ",
      "Doğanşehir",
      "Yazıhan",
      "Pütürge",
      "Arapgir",
      "Hekimhan",
      "Kuluncak",
      "Arguvan",
    ],
  },
  {
    city: "Manisa",
    districts: [
      "Şehzadeler",
      "Yunusemre",
      "Akhisar",
      "Salihli",
      "Turgutlu",
      "Soma",
      "Alaşehir",
      "Saruhanlı",
      "Kula",
      "Demirci",
      "Kırkağaç",
      "Gölmarmara",
      "Selendi",
      "Sarigöl",
      "Gördes",
      "Ahmetli",
    ],
  },
  {
    city: "Mardin",
    districts: [
      "Artuklu",
      "Kızıltepe",
      "Nusaybin",
      "Derik",
      "Mazıdağı",
      "Midyat",
      "Ömerli",
      "Savur",
      "Yeşilli",
      "Dargeçit",
    ],
  },
  {
    city: "Mersin",
    districts: [
      "Akdeniz",
      "Mezitli",
      "Toroslar",
      "Yenişehir",
      "Tarsus",
      "Erdemli",
      "Çamlıyayla",
      "Silifke",
      "Anamur",
      "Bozyazı",
      "Gülnar",
      "Mut",
      "Aydıncık",
    ],
  },
  {
    city: "Muğla",
    districts: [
      "Menteşe",
      "Bodrum",
      "Fethiye",
      "Milas",
      "Marmaris",
      "Datça",
      "Dalaman",
      "Köyceğiz",
      "Ortaca",
      "Ula",
      "Yatağan",
      "Seydikemer",
      "Kavaklıdere",
    ],
  },
  {
    city: "Muş",
    districts: ["Merkez", "Bulanık", "Malazgirt", "Varto", "Hasköy", "Korkut"],
  },
  {
    city: "Nevşehir",
    districts: [
      "Merkez",
      "Ürgüp",
      "Avanos",
      "Gülşehir",
      "Hacıbektaş",
      "Kozaklı",
      "Derinkuyu",
    ],
  },
  {
    city: "Niğde",
    districts: [
      "Merkez",
      "Bor",
      "Çamardı",
      "Ulukışla",
      "Altunhisar",
      "Çiftlik",
    ],
  },
  {
    city: "Ordu",
    districts: [
      "Altınordu",
      "Ünye",
      "Fatsa",
      "Gölköy",
      "Perşembe",
      "Kumru",
      "Mesudiye",
      "Akkuş",
      "Aybastı",
      "Çamaş",
      "Çatalpınar",
      "Çaybaşı",
      "Gülyalı",
      "Gürgentepe",
      "İkizce",
      "Kabadüz",
      "Kabataş",
      "Korgan",
      "Ulubey",
    ],
  },
  {
    city: "Osmaniye",
    districts: [
      "Merkez",
      "Kadirli",
      "Düziçi",
      "Bahçe",
      "Toprakkale",
      "Sumbas",
      "Hasanbeyli",
    ],
  },
  {
    city: "Rize",
    districts: [
      "Merkez",
      "Ardeşen",
      "Çamlıhemşin",
      "Çayeli",
      "Fındıklı",
      "İkizdere",
      "Kalkandere",
      "Pazar",
      "Güneysu",
      "Derepazarı",
      "Hemşin",
      "İyidere",
    ],
  },
  {
    city: "Sakarya",
    districts: [
      "Adapazarı",
      "Akyazı",
      "Ferizli",
      "Geyve",
      "Hendek",
      "Karapürçek",
      "Karasu",
      "Kaynarca",
      "Kocaali",
      "Pamukova",
      "Sapanca",
      "Serdivan",
      "Söğütlü",
      "Taraklı",
    ],
  },
  {
    city: "Samsun",
    districts: [
      "İlkadım",
      "Atakum",
      "Bafra",
      "Çarşamba",
      "Vezirköprü",
      "Terme",
      "Tekkeköy",
      "Havza",
      "Alaçam",
      "19 Mayıs",
      "Ayvacık",
      "Yakakent",
      "Ladik",
      "Asarcık",
    ],
  },
  {
    city: "Siirt",
    districts: [
      "Merkez",
      "Baykan",
      "Eruh",
      "Kurtalan",
      "Pervari",
      "Şirvan",
      "Tillo",
    ],
  },
  {
    city: "Sinop",
    districts: [
      "Merkez",
      "Boyabat",
      "Durağan",
      "Erfelek",
      "Gerze",
      "Ayancık",
      "Türkeli",
      "Dikmen",
      "Saraydüzü",
    ],
  },
  {
    city: "Sivas",
    districts: [
      "Merkez",
      "Şarkışla",
      "Yıldızeli",
      "Suşehri",
      "Gemerek",
      "Zara",
      "Kangal",
      "Gürün",
      "Divriği",
      "Ulaş",
      "Hafik",
      "İmranlı",
      "Akıncılar",
      "Altınyayla",
      "Doğanşar",
      "Gölova",
    ],
  },
  {
    city: "Şanlıurfa",
    districts: [
      "Eyyübiye",
      "Haliliye",
      "Viranşehir",
      "Siverek",
      "Suruç",
      "Akçakale",
      "Birecik",
      "Harran",
      "Bozova",
      "Ceylanpınar",
      "Hilvan",
      "Karaköprü",
    ],
  },
  {
    city: "Şırnak",
    districts: [
      "Merkez",
      "Cizre",
      "Silopi",
      "İdil",
      "Uludere",
      "Beytüşşebap",
      "Güçlükonak",
    ],
  },
  {
    city: "Tekirdağ",
    districts: [
      "Süleymanpaşa",
      "Çerkezköy",
      "Çorlu",
      "Hayrabolu",
      "Malkara",
      "Saray",
      "Şarköy",
      "Kapaklı",
      "Ergene",
      "Marmaraereğlisi",
    ],
  },
  {
    city: "Tokat",
    districts: [
      "Merkez",
      "Turhal",
      "Reşadiye",
      "Zile",
      "Niksar",
      "Erbaa",
      "Almus",
      "Artova",
      "Başçiftlik",
      "Pazar",
      "Sulusaray",
      "Yeşilyurt",
    ],
  },
  {
    city: "Trabzon",
    districts: [
      "Ortahisar",
      "Akçaabat",
      "Araklı",
      "Arsin",
      "Beşikdüzü",
      "Çarşıbaşı",
      "Çaykara",
      "Dernekpazarı",
      "Düzköy",
      "Hayrat",
      "Köprübaşı",
      "Maçka",
      "Of",
      "Sürmene",
      "Şalpazarı",
      "Tonya",
      "Vakfıkebir",
      "Yomra",
    ],
  },
  {
    city: "Tunceli",
    districts: [
      "Merkez",
      "Çemişgezek",
      "Hozat",
      "Mazgirt",
      "Nazımiye",
      "Ovacık",
      "Pertek",
      "Pülümür",
    ],
  },
  {
    city: "Uşak",
    districts: ["Merkez", "Banaz", "Eşme", "Karahallı", "Sivaslı", "Ulubey"],
  },
  {
    city: "Van",
    districts: [
      "İpekyolu",
      "Tuşba",
      "Edremit",
      "Çaldıran",
      "Erciş",
      "Gevaş",
      "Gürpınar",
      "Muradiye",
      "Bahçesaray",
      "Çatak",
      "Özalp",
      "Saray",
    ],
  },
  {
    city: "Yalova",
    districts: [
      "Merkez",
      "Altınova",
      "Armutlu",
      "Çınarcık",
      "Çiftlikköy",
      "Termal",
    ],
  },
  {
    city: "Yozgat",
    districts: [
      "Merkez",
      "Akdağmadeni",
      "Boğazlıyan",
      "Çayıralan",
      "Çekerek",
      "Sarıkaya",
      "Sorgun",
      "Şefaatli",
      "Yerköy",
      "Kadışehri",
      "Aydıncık",
      "Çandır",
      "Yenifakılı",
    ],
  },
  {
    city: "Zonguldak",
    districts: [
      "Merkez",
      "Çaycuma",
      "Devrek",
      "Karabük",
      "Kozlu",
      "Alaplı",
      "Gökçebey",
      "Ereğli",
    ],
  },
];
export default cityDistricts;
